### ISSUE TITLE
Unable to test requests via Postman-like software

### ISSUE THREAD

**Issue by arxdeus** [ArtyomArtamonov/msg#6]
Hi, there's a problem with BloomRPC, Insomnia and other Postman-like software with grpc support

Main problem is that such soft doesn't know how to resolve external imports, as a result of which it swears at the lack of models from the _model.proto_ file

_**Error message:**_ 
```
Error while importing protos
no such Type or Enum 'model.Message' in Type .message.MessageDelivery
```

**Comment by ArtyomArtamonov** [comment]
Hi. I ran into the same problem. The best solution for me was to use Postman. If you have any suggestions, how to use another software in this situation, please leave a comment below. For now, this issue should be closed

**Comment by arxdeus** [comment]
So, i have decided to remove model.proto and import all dependent models directly to api, auth and message protos

Here's i attached fully working protos for all services, it works in BloomRPC well


[msg-proto.zip](https://github.com/ArtyomArtamonov/msg/files/9430142/msg-proto.zip)
