### ISSUE TITLE
[Question] Fate of this project

### ISSUE THREAD

**Issue by arxdeus** [ArtyomArtamonov/msg#8]
Hi, thanks for such a cool example, it really helps to learn a lot

I see that the maintainer responds to issues fairly quickly

Unfortunately, there have been no commits to the project for three months and I am interested in the fate of this project - is it frozen or completely abandoned?

I really hope that the development hasn't been abandoned, cuz it really cool project

Thank you for your reply!

**Comment by ArtyomArtamonov** [comment]
Hello again, thanks for being interested in this project!
When I started it, I wanted to learn grpc and more other stuff I used here. For now, I'm working on another interesting project.
I can't say for sure will I be working on msg again or not. Maybe some time latter
